name: SquatchPVP
main: net.yeticraft.squatingyeti.SquatchPVP.SquatchPVP
version: 1.0
author: Squatingyeti
description: Killers steal money from their victims
startup: postworld
depend: [Vault]
commands:
  pvp:
    description: Used to view PvP stats
    usage: /<command> help
permissions:
  squatchpvp.getpay:
    default: true
    description: Needed to steal money from another Player
  squatchpvp.givepay:
    default: true
    description: Needed to have money stolen from you
  squatchpvp.ignoredeathfee:
    default: op
    description: Do not pay Death Toll when you die
  squatchpvp.sneak:
    default: false
    description: Allows the player to sneak for a fee